let recipes = [
	{
		name: "southern fried chicken burger and chips",
		description: "Southern fried chicken burger with sweet pepper relish, mayonnaise, salad and coleslaw in a toasted sesame seed bun. Served with seasoned fries.",
		img: "images/chick-chips.JPG",
		selection: "meat",
		trending: "yes",
	},
	{
		name: "beef curry",
		description: "Delicious beef curry with a mixture of spices.",
		img: "images/curry.JPG",
		selection: "meat",
		trending: "no",
	},

	{
		name: "butternut squash soup",
		description: "A creamy and tasty soup with toasted seed and homemade bread.",
		img: "images/soup.JPG",
		selection: "vegetarian",
		trending: "yes",
	},
	{
		name: "chicken pesto tagliatelle",
		description: "Roasted chicken with taglietelle and pesto.",
		img: "images/chick-pasta.JPG",
		selection: "meat",
		trending: "yes",
	},
	{
		name: "meatballs and spaghetti",
		description: "Delicious beef meatballs with olives and parmesan with a twist!",
		img: "images/meatballs.JPG",
		selection: "meat",
		trending: "no",
	},
	{
		name: "paella",
		description: "Full of flavour, look no further for a great paella recipe!",
		img: "images/paella.JPG",
		selection: "fish",
		trending: "no",
	},
	{
		name: "teriyaki prawn noodles",
		description: "Sticky and sweet quick and healthy stir fry.",
		img: "images/prawns.JPG",
		selection: "fish",
		trending: "no",
	},
	{
		name: "peppercorn salmon",
		description: "Pan-seared salmon in a rich, creamy peppercorn and paprika sauce.",
		img: "images/salmon.JPG",
		selection: "fish",
		trending: "no",
	},
	{
		name: "artichoke pizza",
		description: "An extra tasty vegetarian pizza with roasted vegetables.",
		img: "images/pizza.JPG",
		selection: "vegetarian",
		trending: "no",
	},
	{
		name: "moroccan chickpeas",
		description: "Full of Moroccan flavours, dates and chickpeas with fragrant, spiced rice.",
		img: "images/chickpeas.JPG",
		selection: "vegetarian",
		trending: "no",
	},
	{
		name: "berry mousse sundae",
		description: "Creamy, sweet and tangy fruit flavours with our delicious sundae.",
		img: "images/berry.JPG",
		selection: "dessert",
		trending: "yes",
	},
	{
		name: "chocolate cheesecake",
		description: "For all choclate lovers with a rich and crunchy base.",
		img: "images/cheesecake.JPG",
		selection: "dessert",
		trending: "no",
	},
	{
		name: "assorted chocolate shortbreads",
		description: "Different flavoured chocolate truffle topped shortbreads.",
		img: "images/chocolate.JPG",
		selection: "dessert",
		trending: "no",
	},
	{
		name: "blueberry pancakes",
		description: "Soft blueberry pancakes with infused syrup.",
		img: "images/pancakes.JPG",
		selection: "dessert",
		trending: "no",
	},
];
